# Generated by Django 5.0.4 on 2024-05-01 18:25

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cartapp', '0002_ordersmodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersmodel',
            name='order_completed_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
